version: '3.4'

services:
  firstapi:
    image: firstapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "8080:80"
    environment:
          secondapiurl: "fasdfasd"
  secondapi:
    image: secondapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "8080:80"
    environment:
          secondapiurl: "fasdfasd"